//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace espn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int Pk { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public Nullable<System.DateTime> GameDate { get; set; }
        public Nullable<int> Gp { get; set; }
        public Nullable<double> Pts { get; set; }
        public Nullable<double> Reb { get; set; }
        public Nullable<double> Ast { get; set; }
        public Nullable<double> Tpm { get; set; }
        public Nullable<double> Tpa { get; set; }
        public Nullable<double> Fga { get; set; }
        public Nullable<double> Fgm { get; set; }
        public Nullable<double> Fta { get; set; }
        public Nullable<double> Ftm { get; set; }
        public Nullable<double> Stl { get; set; }
        public Nullable<double> Blk { get; set; }
        public Nullable<double> To { get; set; }
        public Nullable<double> Min { get; set; }
        public Nullable<double> Pf { get; set; }
        public Nullable<double> FtPer { get; set; }
        public Nullable<double> FgPer { get; set; }
        public Nullable<double> TpPer { get; set; }
        public Nullable<double> Score { get; set; }

        public Game(GameStats gameStats, int pk, int playerId)
        {
            Pk = pk;
            PlayerId = playerId;
            GameDate = gameStats.GameDate;
            Gp = gameStats.Gp;
            Pts = gameStats.Pts;
            Reb = gameStats.Reb;
            Ast = gameStats.Ast;
            Tpm = gameStats.Tpm;
            Tpa = gameStats.Tpa;
            Fga = gameStats.Fga;
            Fgm = gameStats.Fgm;
            Ftm = gameStats.Ftm;
            Fta = gameStats.Fta;
            Stl = gameStats.Stl;
            Blk = gameStats.Blk;
            To = gameStats.To;
            Min = gameStats.Min;
            Pf = gameStats.Pf;
            FtPer = gameStats.FtPer;
            FgPer = gameStats.FgPer;
            TpPer = gameStats.TpPer;
        }
    }
}
