//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace espn
{
    using System;
    using System.Collections.Generic;

    public partial class Player
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Team { get; set; }
        public Nullable<int> Age { get; set; }
        public string Misc { get; set; }
        public Nullable<long> Type { get; set; }

        public Player()
        {

        }

        public Player(PlayerInfo playerInfo)
        {
            ID = playerInfo.Id;
            Name = playerInfo.PlayerName;
            Team = playerInfo.Team;
            Age = playerInfo.Age;
            Misc = playerInfo.Misc;
            Type = playerInfo.Type;
        }
    }
}
